import type { BlogPostConfig } from "@/types";

// 11 blog posts — slugs preserved verbatim from the legacy advantageairokc.com Webflow site.
// Content adapted and rewritten for clarity around the original topic of each post.
export const blogPosts: BlogPostConfig[] = [
  {
    slug: "a-beginners-guide-to-hvac-installation-what-to-expect",
    title: "A Beginner's Guide to HVAC Installation: What to Expect",
    excerpt:
      "If you've never replaced an HVAC system before, the process can feel intimidating. Here's a clear walk-through of what actually happens — from the first phone call to the final walkthrough.",
    date: "2024-08-12",
    readTime: "6 min read",
    heroImage: "service-ac-install-feature",
    body: [
      { type: "p", text: "Replacing an HVAC system is one of the bigger investments most homeowners ever make in their homes — and if you've never done it before, the process can feel like a black box. Knowing what to expect makes the whole experience smoother and helps you ask the right questions when you're getting quotes." },
      { type: "p", text: "Below is a step-by-step look at what a typical residential HVAC install looks like when it's done right." },
      { type: "h2", text: "Step 1 — The In-Home Estimate" },
      { type: "p", text: "Every quality install starts with an in-home visit. A good contractor will spend 30–60 minutes at your house — measuring rooms, looking at your existing equipment and ductwork, asking about hot/cold spots, checking your electrical panel, and getting a feel for how you actually use the home." },
      { type: "p", text: "Beware of any contractor who quotes you a system size or a price over the phone without ever stepping inside. Sizing matters more than almost anything else, and it can't be done remotely." },
      { type: "h2", text: "Step 2 — The Load Calculation" },
      { type: "p", text: "A load calculation (often called a Manual J) accounts for your home's square footage, insulation, window count, ceiling height, sun exposure, and your local climate. The result tells your contractor how much heating and cooling capacity your home actually needs — not too much, not too little." },
      { type: "p", text: "An oversized AC short-cycles, doesn't dehumidify well, and wears out faster. An undersized unit runs constantly and never quite catches up on the hottest days. Right-sizing is the single biggest factor in long-term comfort and bills." },
      { type: "h2", text: "Step 3 — The Written Proposal" },
      { type: "p", text: "You should walk away from the in-home visit with — or shortly receive — a written proposal. It should clearly list the equipment make and model, the system tonnage and efficiency rating, included accessories (like a new thermostat), warranty terms, and the total price." },
      { type: "p", text: "If a quote is one number with nothing itemized, ask for a breakdown. You're entitled to know what you're paying for." },
      { type: "h2", text: "Step 4 — Install Day" },
      { type: "p", text: "On install day, expect a crew of 2–3 technicians for most residential jobs. They'll arrive in the morning, lay drop cloths and floor protection, remove the old equipment, and get the new system in." },
      { type: "p", text: "A typical full system replacement (outdoor condenser plus indoor coil and/or furnace) takes 4–8 hours. The crew should also handle: a new condensate drain line, refrigerant line set, electrical disconnect upgrade if needed, a new outdoor pad, and a fresh thermostat." },
      { type: "h2", text: "Step 5 — Commissioning & Walkthrough" },
      { type: "p", text: "Before they leave, the lead technician should commission the system — checking refrigerant charge, measuring airflow at the supply registers, verifying the thermostat is wired correctly, and walking through the equipment with you." },
      { type: "p", text: "You should know how to change the filter, how to use the new thermostat, what your warranty terms are, and who to call if anything goes sideways." },
      { type: "h2", text: "What to Watch Out For" },
      { type: "ul", items: [
        "Quotes given over the phone with no in-home visit",
        "Contractors pushing the cheapest equipment without explaining trade-offs",
        "No load calculation — just guessing at system size",
        "Vague warranty language",
        "Sub-contracted installers you've never met before",
      ]},
      { type: "p", text: "A new HVAC system installed properly should give you 12–15+ years of comfortable, low-maintenance service. The install itself is what makes that possible — choose a contractor who treats it that way." },
    ],
  },

  {
    slug: "bracing-for-the-chill",
    title: "Bracing for the Chill: Getting Your Home Ready for Oklahoma Winter",
    excerpt:
      "Oklahoma winters can flip from mild to brutal in a single week. Here's how to prep your home, your heating system, and your pipes before the temperature drops.",
    date: "2024-10-22",
    readTime: "5 min read",
    heroImage: "service-heating-feature",
    body: [
      { type: "p", text: "Oklahoma winters are unpredictable. We can have weeks of mild, sweater-weather afternoons followed by a single ice storm or polar vortex that drops temperatures into the single digits. The homes that hold up best in those swings are the ones whose owners did a few hours of prep in October or November." },
      { type: "h2", text: "Schedule a Heating Tune-Up Before You Need It" },
      { type: "p", text: "An annual heating tune-up is the single most cost-effective thing you can do. A NATE-certified technician will clean the burners, check the heat exchanger for cracks, test the flame sensor, verify gas pressure, and confirm the system is running safely and efficiently. Most issues that cause winter breakdowns are visible during a tune-up." },
      { type: "p", text: "Schedule it in October or early November — you don't want to be on a waiting list when your heater quits during an ice storm." },
      { type: "h2", text: "Replace the Air Filter" },
      { type: "p", text: "A clogged air filter is the most common cause of heating problems. It restricts airflow, makes the system overheat, trips safety switches, and shortens equipment life. Replace yours every 30–90 days depending on filter thickness and household conditions." },
      { type: "h2", text: "Reverse the Ceiling Fans" },
      { type: "p", text: "Most ceiling fans have a small switch on the motor housing. Flip it so the blades spin clockwise (looking up) — this gently pushes warm air down from the ceiling without creating a draft. It's a free comfort upgrade." },
      { type: "h2", text: "Insulate Outdoor Pipes" },
      { type: "p", text: "Hose bibs, exposed pipes in the garage or crawl space, and pipes in exterior walls are at risk during cold snaps. Foam pipe insulation is cheap and easy. Disconnect garden hoses before the first hard freeze." },
      { type: "h2", text: "Test Your Carbon Monoxide Detectors" },
      { type: "p", text: "Gas furnaces produce carbon monoxide as a normal byproduct of combustion. Functioning CO detectors are non-negotiable. Test them, replace batteries, and replace the detector itself if it's more than 7–10 years old." },
      { type: "h2", text: "Have a Backup Plan" },
      { type: "p", text: "Even with everything done right, equipment can fail at the worst times. Save the number of an HVAC contractor that actually answers the phone 24/7 — and program it before you need it. Having to look one up in a crisis is no fun." },
      { type: "p", text: "A few hours of prep now means a more comfortable, safer, lower-stress winter. And if something does go sideways, Advantage Heating & Air Conditioning is on call 24/7, 365 days a year — including ice storms and the inevitable cold snaps." },
    ],
  },

  {
    slug: "understanding",
    title: "Understanding the Core Principles Behind HVAC Systems",
    excerpt:
      "What's actually happening when your heater turns on or your AC starts cooling? A plain-English look at the physics that drive every HVAC system.",
    date: "2024-06-18",
    readTime: "7 min read",
    heroImage: "service-vent-feature",
    body: [
      { type: "p", text: "HVAC stands for Heating, Ventilation, and Air Conditioning. Most people think of it as one big system, but it's actually a network of components working together to do three jobs: keep your home warm, keep it cool, and move air through it cleanly. Understanding the basics makes it easier to spot problems early and have smarter conversations with your contractor." },
      { type: "h2", text: "Heating: Generating Warmth" },
      { type: "p", text: "Most homes in Oklahoma City heat with a gas furnace. The furnace burns natural gas in a sealed combustion chamber, the heat from that combustion warms a metal heat exchanger, and a blower fan pushes household air across the heat exchanger and through your ductwork — picking up the heat on the way." },
      { type: "p", text: "Heat pumps work differently. Instead of generating heat by burning fuel, they move heat from one place to another using refrigerant. In winter, a heat pump pulls heat from the outdoor air (yes, even cold air contains heat) and brings it inside. In summer, it reverses and dumps indoor heat outside — same as an AC." },
      { type: "h2", text: "Cooling: Moving Heat Out of the House" },
      { type: "p", text: "Your AC doesn't \"create cold.\" It moves heat from inside your house to outside. That's why the outdoor unit (the condenser) is hot during operation — it's where the indoor heat ends up." },
      { type: "p", text: "A refrigerant circulates between the indoor coil (in your air handler) and the outdoor coil. The indoor coil is cold, so when warm household air blows across it, the air gets cooled and the refrigerant absorbs the heat. That refrigerant is then pumped outside, where the heat is released, and the cycle repeats." },
      { type: "h2", text: "Ventilation: Keeping Air Moving" },
      { type: "p", text: "Ventilation is the often-overlooked third leg of HVAC. It's how air moves into, out of, and through your home. Properly designed ductwork ensures conditioned air reaches every room. Bath and kitchen exhaust fans remove moisture and odors. Whole-home filtration and fresh-air intakes keep indoor air healthy." },
      { type: "h2", text: "How They Work Together" },
      { type: "p", text: "Your thermostat is the brain. When the indoor temperature drifts away from your setpoint, the thermostat sends a signal to either the furnace or AC to start running. The blower fan pushes air through the ductwork, the supply registers deliver conditioned air to each room, and the return air grilles pull air back to be reconditioned." },
      { type: "p", text: "The whole system depends on balanced airflow. Closed registers, undersized ducts, leaky returns, and clogged filters all undermine the system you paid good money for." },
      { type: "h2", text: "Why It Matters" },
      { type: "p", text: "When you understand what your system is supposed to be doing, you notice problems faster. Weak airflow, strange noises, ice on the coil, water around the indoor unit, and rooms that won't catch up on hot or cold days are all symptoms of specific underlying issues — not random misbehavior." },
      { type: "p", text: "If something seems off, get it diagnosed. Small issues caught early stay small. Ignored, they tend to take down the whole system." },
    ],
  },

  {
    slug: "the-evolution-of-hvac-from-ancient-techniques-to-modern-comfort-solutions",
    title: "The Evolution of HVAC: From Ancient Techniques to Modern Comfort Solutions",
    excerpt:
      "Indoor climate control isn't new — humans have been engineering comfort for thousands of years. A look at how heating and cooling went from open fires to smart thermostats.",
    date: "2024-05-30",
    readTime: "6 min read",
    heroImage: "img-air-duct-vent",
    body: [
      { type: "p", text: "Humans have been trying to control indoor temperatures for as long as we've had indoor spaces. The journey from ancient hearth fires to today's variable-speed inverter systems is a fun one — and it explains a lot about why modern HVAC works the way it does." },
      { type: "h2", text: "Ancient Cooling: Architecture as Air Conditioning" },
      { type: "p", text: "Long before electricity, ancient builders designed their way to comfort. The Romans circulated water through walls in some wealthy homes. Persian builders engineered wind catchers (badgirs) — tall towers that funneled cooler high-altitude air down into living spaces. Arched courtyards, thick walls, narrow streets — all of it was passive climate engineering." },
      { type: "h2", text: "Ancient Heating: Fire and Hypocausts" },
      { type: "p", text: "Heating was simpler — at first, just open fires under chimneys. The Romans took it further with the hypocaust: raised floors with hot air channels underneath, fed by furnaces. Effectively the world's first radiant floor heating, more than 2,000 years before modern hydronic systems." },
      { type: "h2", text: "The Industrial Era and the Birth of Refrigeration" },
      { type: "p", text: "Mechanical refrigeration started in the 1830s with vapor-compression cycles in commercial cold storage. By 1902, Willis Carrier built the first modern air conditioning system — designed not for comfort, but to control humidity in a Brooklyn printing plant whose paper kept warping in summer." },
      { type: "p", text: "Comfort cooling for ordinary homes didn't take off until the 1950s, when window AC units became affordable enough for middle-class budgets. Central AC followed in the 1960s." },
      { type: "h2", text: "Modern Heating Equipment" },
      { type: "p", text: "Furnaces evolved from coal- and wood-burners to natural gas, then to high-efficiency condensing models that capture heat from the flue gas instead of letting it escape. Today's 95%+ AFUE furnaces use about 30% less fuel than the standard furnaces of the 1980s." },
      { type: "p", text: "Heat pumps, originally a niche product, have improved dramatically. Modern inverter-driven heat pumps can heat a home efficiently down to 5°F or below — making them practical for most of the country." },
      { type: "h2", text: "Smart Controls" },
      { type: "p", text: "The thermostat went from a bimetallic strip with a mercury switch to programmable digital units in the 90s, to today's Wi-Fi-connected, occupancy-sensing, machine-learning smart thermostats that figure out your routine and run your equipment efficiently around it." },
      { type: "h2", text: "What's Next" },
      { type: "p", text: "Variable-refrigerant-flow (VRF) systems, low-GWP refrigerants, geothermal expansion, and ever-tighter integration with home solar are all in motion. The next decade of HVAC is going to be quieter, more efficient, and more responsive — but the basic physics behind it is the same one the Romans were starting to work out 2,000 years ago." },
    ],
  },

  {
    slug: "the-future-is-smart-how-smart-thermostats-improve-hvac-efficiency",
    title: "The Future Is Smart: How Smart Thermostats Improve HVAC Efficiency",
    excerpt:
      "A modern smart thermostat can shave 10–20% off your annual heating and cooling bills — if you set it up right. Here's how they actually work and what to look for.",
    date: "2024-09-04",
    readTime: "5 min read",
    heroImage: "service-vent-mini-split",
    body: [
      { type: "p", text: "A good smart thermostat does three things at once: it learns your schedule, it gives you remote control over the system, and it helps your HVAC equipment run as efficiently as possible. For most homeowners, the payback is within a single year of energy savings." },
      { type: "h2", text: "How Smart Thermostats Save Energy" },
      { type: "p", text: "Smart thermostats save energy in a few ways. First, they automatically lower the setpoint when no one is home — using motion sensors, geofencing, or learned schedules. A consistent 7–10°F setback for 8 hours a day can cut about 10% off your heating and cooling costs." },
      { type: "p", text: "Second, they handle smart pre-conditioning. Instead of slamming the system on at 5 PM when you walk in the door, they ramp it up gradually beforehand — keeping the house comfortable while running the equipment less aggressively." },
      { type: "p", text: "Third, many models support multi-stage equipment intelligently — running a high-efficiency furnace or AC at low stage when possible to maintain comfort with less energy." },
      { type: "h2", text: "What to Look For" },
      { type: "ul", items: [
        "Compatibility with your specific HVAC equipment (especially heat pumps and multi-stage furnaces — not all thermostats are wired the same)",
        "A C-wire (common wire) at your existing thermostat — required by most smart models",
        "Wi-Fi and a real mobile app (not just a clunky web portal)",
        "Geofencing or occupancy sensing",
        "Useful integrations (Alexa, Google Home, HomeKit)",
        "Easy schedule editing on the device itself, not just the app",
      ]},
      { type: "h2", text: "Top Models for OKC Homes" },
      { type: "p", text: "Three options dominate the market: Google Nest, Ecobee, and Honeywell Home (T9 / T10). All three are good — the right one depends on what ecosystem you're in and how complex your equipment is." },
      { type: "p", text: "Heat pumps with auxiliary heat or dual-fuel systems are best paired with Ecobee or Honeywell — both handle staging better than Nest. Single-stage gas furnaces with single-stage AC work fine on any of them." },
      { type: "h2", text: "Installation" },
      { type: "p", text: "Many homeowners install smart thermostats themselves — but a botched install can trip a low-voltage transformer or short out the control board on your furnace. If your existing thermostat doesn't have a C-wire, or if you have a multi-stage or heat-pump system, get it installed by a pro. The cost is usually $100–$200 and includes a quick verification that everything is wired right." },
      { type: "p", text: "Done correctly, a smart thermostat is one of the easiest, most cost-effective HVAC upgrades you'll ever make." },
    ],
  },

  {
    slug: "mastering-your-hvac-system-the-ultimate-guide-to-year-round-comfort",
    title: "Mastering Your HVAC System: The Ultimate Guide to Year-Round Comfort",
    excerpt:
      "Comfort isn't just about set points — it's about humidity, airflow, equipment health, and habits. Here's how to get your system running great in every season.",
    date: "2024-04-15",
    readTime: "8 min read",
    heroImage: "service-ac-install-feature",
    body: [
      { type: "p", text: "Most homes have rooms that are too hot in summer, too cold in winter, dusty year-round, or all of the above. The fix is rarely \"buy a bigger system\" — it's a combination of small tuning, equipment health, and a few habits that add up." },
      { type: "h2", text: "Get the Basics Right" },
      { type: "p", text: "Change the air filter every 30–90 days. Keep supply registers and return grilles clear of furniture and curtains. Use ceiling fans (counterclockwise in summer, clockwise in winter). Don't close vents in unused rooms — modern systems are designed for fully open returns and supplies." },
      { type: "h2", text: "Schedule Twice-Yearly Maintenance" },
      { type: "p", text: "Heating tune-up in fall, AC tune-up in spring. A NATE-certified technician should be cleaning the burner or coils, checking refrigerant charge or gas pressure, verifying safety controls, and inspecting electrical connections. This single habit prevents most major breakdowns." },
      { type: "h2", text: "Tame Humidity" },
      { type: "p", text: "Oklahoma summers are humid. An AC that's properly sized and tuned will pull water out of the air as it cools — but oversized units short-cycle and don't dehumidify well, and undersized units run nonstop and never get ahead. If your house feels clammy at 75°F, humidity is the culprit." },
      { type: "p", text: "Some homes benefit from a whole-home dehumidifier installed in line with the HVAC system. It runs independently of the thermostat and pulls humidity even when the AC isn't calling for cooling." },
      { type: "h2", text: "Fix the Hot/Cold Rooms" },
      { type: "p", text: "Rooms that won't catch up are usually a ductwork or balancing issue, not a system size issue. The solutions:" },
      { type: "ul", items: [
        "Have a tech do a static-pressure and airflow test to find the actual problem room",
        "Add a dedicated return air grille to over-pressurized rooms",
        "Resize or reroute supply ducts to under-served rooms",
        "Install dampers and balance the system",
        "For real outliers (additions, sunrooms, garages), a ductless mini-split is often the right answer",
      ]},
      { type: "h2", text: "Upgrade the Filtration" },
      { type: "p", text: "The standard 1-inch filter most homes use is mediocre at best. A 4–5 inch media filter cabinet (installed in line with your air handler) lasts 6–12 months between changes and captures dramatically more dust, dander, and pollen — without restricting airflow the way a thick 1-inch filter would." },
      { type: "h2", text: "Manage the Setpoint Smart" },
      { type: "p", text: "A 7–10°F setback for 8 hours a day saves about 10% per year on heating and cooling. Smart thermostats automate this — and they're one of the cheaper, faster-payback upgrades you can make." },
      { type: "h2", text: "Plan for Replacement Before You Have To" },
      { type: "p", text: "Average HVAC equipment lasts 12–18 years depending on use, maintenance, and climate. If your system is over 12 years old and starting to need real repairs, start pricing replacement so you're not making a panic decision when it dies on the hottest day of the year." },
      { type: "p", text: "Comfort, efficiency, and peace of mind all come from doing the small stuff consistently. Done right, your HVAC system can fade into the background — exactly where it belongs." },
    ],
  },

  {
    slug: "the-top-10-signs-your-hvac-system-needs-professional-attention",
    title: "The Top 10 Signs Your HVAC System Needs Professional Attention",
    excerpt:
      "HVAC systems rarely fail without warning. Here are 10 specific symptoms that mean it's time to call a technician — before a small problem turns into an expensive one.",
    date: "2024-07-22",
    readTime: "6 min read",
    heroImage: "service-ac-repair-feature",
    body: [
      { type: "p", text: "Most major HVAC failures give you weeks or months of warning signs first. Catching those signs early is the difference between a $200 repair and a $4,000 replacement. Here are the ones to watch for." },
      { type: "h2", text: "1. Weak Airflow" },
      { type: "p", text: "If air is barely whispering out of your supply registers, you've got a problem. Causes range from a clogged filter (cheap fix) to a failing blower motor, restricted ductwork, or refrigerant issues (not cheap)." },
      { type: "h2", text: "2. Warm Air from the AC" },
      { type: "p", text: "Most often this is low refrigerant from a slow leak, a frozen evaporator coil, or a failed capacitor. Don't keep running it — you can damage the compressor." },
      { type: "h2", text: "3. Strange Noises" },
      { type: "p", text: "Banging, squealing, grinding, or rumbling are not normal. Each sound usually points to a specific component. The longer you run a noisy unit, the more secondary damage you cause." },
      { type: "h2", text: "4. Bad Smells" },
      { type: "p", text: "Burning smells (electrical), rotten egg (gas leak — leave the house, call your gas utility), musty (mold in the ductwork), or vinegar/sour (microbial growth on the coil). All deserve attention." },
      { type: "h2", text: "5. Short-Cycling" },
      { type: "p", text: "If your system turns on and off every few minutes, something's wrong. Common causes: oversized equipment, dirty filter, bad thermostat placement, or refrigerant problems." },
      { type: "h2", text: "6. Rising Power Bills" },
      { type: "p", text: "If your bills are climbing while your usage habits aren't, your system is working harder than it should. Causes range from a dirty coil to leaking ducts to a refrigerant problem to age-related efficiency loss." },
      { type: "h2", text: "7. Uneven Temperatures" },
      { type: "p", text: "If some rooms are great and others won't catch up, you likely have a ductwork or balancing issue. Sometimes it's a failing blower or zone damper." },
      { type: "h2", text: "8. Excessive Humidity" },
      { type: "p", text: "A working AC dehumidifies as it cools. If your house feels muggy at the right temperature, your system isn't pulling moisture properly — usually a sizing or refrigerant issue." },
      { type: "h2", text: "9. Water Around the Indoor Unit" },
      { type: "p", text: "Water on the floor near your air handler usually means a clogged condensate drain or a frozen and thawed coil. Both need attention quickly — water damage to floors and ceilings can cost more than the original repair." },
      { type: "h2", text: "10. Age + Frequent Repairs" },
      { type: "p", text: "If your system is over 12 years old and you've called for service multiple times in the last two years, you're spending money on a depreciating asset. Get an honest replacement quote and compare." },
      { type: "p", text: "When in doubt, schedule a service visit. A $150 diagnostic call now can save you thousands in compounding damage and emergency replacement later." },
    ],
  },

  {
    slug: "the-professional-touch-when-to-call-in-the-experts",
    title: "The Professional Touch: When to Call in the HVAC Experts",
    excerpt:
      "Some HVAC tasks are great DIY projects. Others can void your warranty or hurt you. Here's a clear line between what to handle yourself and what to leave to a pro.",
    date: "2024-08-28",
    readTime: "5 min read",
    heroImage: "img-mini-split-clean",
    body: [
      { type: "p", text: "There's plenty you can — and should — do yourself to keep your HVAC system healthy. There's also a clear line beyond which DIY moves from saving money to costing it. Here's how to tell which side you're on." },
      { type: "h2", text: "Things You Should Do Yourself" },
      { type: "ul", items: [
        "Replace the air filter on schedule (every 30–90 days)",
        "Keep supply registers and return grilles unblocked",
        "Hose off the outdoor condenser fins gently with a garden hose (no pressure washer)",
        "Keep landscaping cut back from the outdoor unit",
        "Replace your thermostat batteries when prompted",
        "Set up your smart thermostat schedule",
        "Run a dehumidifier in problem areas",
      ]},
      { type: "h2", text: "Things You Should Probably Not Do Yourself" },
      { type: "ul", items: [
        "Anything involving refrigerant — it's federally regulated and you can't legally buy R-410A or R-32 without certification",
        "Opening up the air handler or furnace (electrical and gas hazards)",
        "Replacing capacitors or contactors (capacitors hold a lethal charge even when power is off)",
        "Anything involving the gas line",
        "Diagnosing why your AC is freezing up (it's almost never the cause you'd guess)",
        "Re-balancing ductwork or installing new returns",
      ]},
      { type: "h2", text: "Why It Matters" },
      { type: "p", text: "DIY HVAC work can void your manufacturer warranty. Most warranties require professional service by a licensed contractor — and proof of annual professional maintenance for full warranty coverage. A well-meaning afternoon with YouTube can cost you a multi-thousand-dollar warranty claim later." },
      { type: "h2", text: "There's Also a Safety Issue" },
      { type: "p", text: "Capacitors store enough charge to seriously hurt you. Cracked heat exchangers leak carbon monoxide. Wiring mistakes can fry control boards. Refrigerant systems are pressurized and can release dangerously if mishandled." },
      { type: "h2", text: "When in Doubt, Get a Diagnosis" },
      { type: "p", text: "Most reputable HVAC contractors will come out for a small diagnostic fee, give you a written quote, and let you decide what to do. If it's a simple fix, the visit is cheap insurance. If it's bigger, you've got real information to make a decision with." },
      { type: "p", text: "Save your DIY energy for the things that genuinely don't require professional expertise. Filters, fan coils, and yard cleanup are great DIY. Refrigerant, gas, and electrical are not." },
    ],
  },

  {
    slug: "keep-it-cool-the-essential-hvac-maintenance-checklist-for-homeowners",
    title: "Keep It Cool: The Essential HVAC Maintenance Checklist for Homeowners",
    excerpt:
      "A simple seasonal maintenance checklist that keeps your system running efficiently and catches small problems before they become big ones.",
    date: "2024-03-11",
    readTime: "4 min read",
    heroImage: "service-ac-install",
    body: [
      { type: "p", text: "Routine maintenance is the difference between an HVAC system that lasts 18 years and one that limps to 10. Here's a season-by-season checklist that any homeowner can follow." },
      { type: "h2", text: "Monthly (or Every 30–90 Days)" },
      { type: "ul", items: [
        "Inspect and replace the air filter as needed",
        "Look at the outdoor unit — clear leaves, grass clippings, and debris",
        "Confirm vents are open and unblocked in every room",
      ]},
      { type: "h2", text: "Spring (Before AC Season)" },
      { type: "ul", items: [
        "Schedule a professional AC tune-up",
        "Hose off the outdoor condenser fins (no pressure washer)",
        "Test the AC in cool mode before the first hot day",
        "Listen for new sounds, watch for water near the indoor unit",
        "Switch your ceiling fans to counterclockwise (summer mode)",
      ]},
      { type: "h2", text: "Summer (Peak Cooling)" },
      { type: "ul", items: [
        "Keep filters fresh — heat is hard on systems",
        "Watch for ice on the indoor coil or refrigerant lines (call a pro if you see ice)",
        "Check that water is draining from the condensate line outside",
        "Use shades or blinds in direct sun rooms to reduce load",
      ]},
      { type: "h2", text: "Fall (Before Heating Season)" },
      { type: "ul", items: [
        "Schedule a professional heating tune-up",
        "Test your CO detectors",
        "Switch ceiling fans to clockwise (winter mode)",
        "Insulate exposed pipes and outdoor faucets",
        "Test the heat in advance — don't wait until it's 25°F outside",
      ]},
      { type: "h2", text: "Winter (Peak Heating)" },
      { type: "ul", items: [
        "Keep filters fresh",
        "Listen for new sounds during start-up cycles",
        "Watch for short-cycling (system turning on/off every few minutes)",
        "Don't close vents in unused rooms",
      ]},
      { type: "h2", text: "Annual" },
      { type: "ul", items: [
        "Two professional tune-ups (spring + fall)",
        "Walk-around inspection of outdoor unit and ductwork",
        "Check thermostat batteries",
        "Document service visits — they support your manufacturer warranty",
      ]},
      { type: "p", text: "Most maintenance is small, cheap, and easy. Done consistently, it adds years to the life of your system and pays for itself many times over in lower bills and avoided breakdowns." },
    ],
  },

  {
    slug: "the-ultimate-hvac-buyers-guide-how-to-choose-the-right-system-for-your-home",
    title: "The Ultimate HVAC Buyer's Guide: How to Choose the Right System for Your Home",
    excerpt:
      "A clear-eyed guide to picking the right HVAC equipment for your home — what efficiency ratings actually mean, when to spring for a heat pump, and what to skip.",
    date: "2024-02-19",
    readTime: "9 min read",
    heroImage: "service-ac-install-hero",
    body: [
      { type: "p", text: "Buying a new HVAC system is one of the more confusing major purchases most homeowners make. Lots of jargon, lots of brands, lots of contractors with different opinions. Here's how to cut through it." },
      { type: "h2", text: "Step 1 — Decide on Equipment Type" },
      { type: "p", text: "Three main configurations to consider for an Oklahoma City home:" },
      { type: "h3", text: "Gas Furnace + Central AC" },
      { type: "p", text: "The most common setup. Cheapest upfront, simple, reliable. Gas heats are inexpensive to operate when natural gas is cheap; AC handles the cooling. Good fit for most OKC homes." },
      { type: "h3", text: "Heat Pump (All-Electric)" },
      { type: "p", text: "One outdoor unit handles both heating and cooling. More efficient than electric resistance heat. Modern inverter heat pumps perform well down to about 5°F before backup heat is needed. A solid choice for all-electric homes or when natural gas isn't available." },
      { type: "h3", text: "Dual-Fuel (Heat Pump + Gas Furnace)" },
      { type: "p", text: "Best of both worlds. Heat pump handles mild weather efficiently; gas furnace kicks in for the coldest nights. Higher upfront cost but lower year-round operating cost in mixed climates like Oklahoma." },
      { type: "h2", text: "Step 2 — Pick a Capacity (Tonnage / BTUs)" },
      { type: "p", text: "This is non-negotiable: your contractor must do a Manual J load calculation. Don't accept \"we'll match what's there now\" as a sizing strategy — many existing systems are oversized or undersized, and you'll inherit the same comfort problems." },
      { type: "h2", text: "Step 3 — Decide on Efficiency Tier" },
      { type: "p", text: "Cooling efficiency is measured in SEER2 (Seasonal Energy Efficiency Ratio v2). Heating efficiency is AFUE (Annual Fuel Utilization Efficiency) for furnaces or HSPF2 for heat pumps. Higher is better — but the math doesn't always favor the highest tier." },
      { type: "ul", items: [
        "14–15 SEER2: minimum efficiency, lowest cost. Fine for budget builds.",
        "16–17 SEER2: solid mid-range. Best value for most OKC homes.",
        "18–22 SEER2: high-efficiency variable speed. Quietest, best dehumidification, biggest energy savings — at the highest upfront cost. Best ROI in extreme climates or homes you'll keep 10+ years.",
      ]},
      { type: "h2", text: "Step 4 — Single, Two-Stage, or Variable Speed" },
      { type: "p", text: "Single-stage equipment is on or off. Two-stage runs at a low setting most of the time and ramps up on hot days. Variable-speed continuously modulates output. Two-stage and variable-speed run quieter, dehumidify better, and maintain steadier temperatures — but cost more upfront." },
      { type: "h2", text: "Step 5 — Pick a Brand" },
      { type: "p", text: "All major brands (Carrier, Trane, Lennox, Goodman, Amana, York, Rheem, Bryant) build reliable equipment in similar tiers. The biggest factor in long-term reliability is the install quality, not the badge on the side." },
      { type: "p", text: "What you should care about more than the brand: who's installing it, what warranty they offer, and how long they've been in business locally. A great install on mid-tier equipment will outlast a mediocre install on premium equipment." },
      { type: "h2", text: "Step 6 — Get 2–3 Quotes" },
      { type: "p", text: "Get quotes from 2–3 reputable contractors. Compare apples to apples on equipment make/model, efficiency, capacity, included accessories, warranty, and total price. The lowest quote is rarely the best value; the highest isn't either." },
      { type: "h2", text: "Step 7 — Ask About Financing" },
      { type: "p", text: "Most major contractors offer financing on qualifying installs. A monthly payment can make a higher-tier system more accessible without straining cash flow." },
      { type: "h2", text: "Bottom Line" },
      { type: "p", text: "For most OKC homes, the sweet spot is a 16–17 SEER2 two-stage AC paired with a 95%+ AFUE gas furnace, properly sized via Manual J, installed by a local contractor with a strong warranty. Nail the install, and the equipment will pay you back for 15+ years." },
    ],
  },

  {
    slug: "maximizing-energy-efficiency-tips-for-lowering-your-hvac-costs",
    title: "Maximizing Energy Efficiency: Tips for Lowering Your HVAC Costs",
    excerpt:
      "Concrete, ranked steps to lower your monthly heating and cooling bills — from free habits to the upgrades worth paying for.",
    date: "2024-01-08",
    readTime: "6 min read",
    heroImage: "img-condenser-closeup",
    body: [
      { type: "p", text: "If your power bills are eating into your budget, there's a lot you can do — and most of the high-impact moves don't require buying new equipment. Here are the best moves, ranked by ROI." },
      { type: "h2", text: "Free or Near-Free" },
      { type: "h3", text: "Replace the Air Filter" },
      { type: "p", text: "A clogged filter restricts airflow, makes your system work harder, and costs you money every month. Replace yours every 30–90 days." },
      { type: "h3", text: "Set the Thermostat Smarter" },
      { type: "p", text: "Every degree you raise the cooling setpoint or lower the heating setpoint saves about 1–3% on energy. A 7–10°F setback for 8 hours a day saves around 10% per year. Smart thermostats automate this." },
      { type: "h3", text: "Use Ceiling Fans" },
      { type: "p", text: "Fans don't change room temperature, but they make you feel cooler — letting you raise the AC setpoint by 2–4°F with no comfort penalty." },
      { type: "h3", text: "Close the Blinds in Direct Sun" },
      { type: "p", text: "Direct sun through windows can add the equivalent of a small space heater to a room. Close blinds, drapes, or solar shades on west-facing windows during summer afternoons." },
      { type: "h2", text: "Cheap Upgrades" },
      { type: "h3", text: "Smart Thermostat" },
      { type: "p", text: "$150–$250 installed. Saves 10–20% on bills. Payback usually under 18 months. Install it." },
      { type: "h3", text: "Weatherstripping and Caulking" },
      { type: "p", text: "Air leaks around doors, windows, and outlets are pulling money out of your wallet every month. Pick up a tube of caulk and a roll of weatherstripping — a Saturday afternoon will tighten the whole house." },
      { type: "h3", text: "Insulate Your Attic" },
      { type: "p", text: "Most older homes are under-insulated up top. Adding blown-in cellulose or fiberglass to bring the attic up to R-49 is one of the best dollar-per-energy-saved moves you can make. Often qualifies for utility rebates." },
      { type: "h2", text: "Bigger Investments Worth Considering" },
      { type: "h3", text: "Schedule Twice-Yearly HVAC Tune-Ups" },
      { type: "p", text: "$80–$150 per visit. Keeps your equipment running near peak efficiency, catches small problems early, and protects your manufacturer warranty. Easy ROI." },
      { type: "h3", text: "Seal Your Ductwork" },
      { type: "p", text: "If your ducts run through an unconditioned attic or crawl space, leaky joints can be costing you 20–30% of your conditioned air. Professional duct sealing or Aeroseal-style treatments can pay back in 2–4 years." },
      { type: "h3", text: "Replace 12+ Year-Old Equipment" },
      { type: "p", text: "Modern 16+ SEER2 equipment uses 30–50% less energy than 14 SEER (or older 10 SEER) equipment. If you're getting close to replacement anyway, the energy savings are real." },
      { type: "h2", text: "What Not to Bother With" },
      { type: "ul", items: [
        "Closing vents in unused rooms (modern systems aren't designed for it; can damage equipment)",
        "Window AC units to avoid running central air (usually less efficient per BTU)",
        "Heat pump 'cold-climate' models for OKC (overkill — standard models handle our winters fine)",
      ]},
      { type: "p", text: "Stack the free habits first, add the cheap upgrades, and consider the bigger investments only when they make sense for your situation. Combined, they can knock 20–40% off your annual heating and cooling bills." },
    ],
  },
];

export function getBlogPostBySlug(slug: string): BlogPostConfig | undefined {
  return blogPosts.find((p) => p.slug === slug);
}
