import { readdir, stat, mkdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join, parse } from "node:path";
import sharp from "sharp";

const ROOT = fileURLToPath(new URL("../public/images/", import.meta.url));
const OUT_DIR = fileURLToPath(new URL("../public/images/_opt/", import.meta.url));
const PUBLIC_DIR = fileURLToPath(new URL("../public/", import.meta.url));
const MANIFEST_PATH = fileURLToPath(new URL("../src/lib/imageVariants.generated.ts", import.meta.url));

const EXTRA_PNGS = [
  { src: join(PUBLIC_DIR, "logo.png"), basename: "logo", widths: [420, 840] },
  { src: join(PUBLIC_DIR, "penguin.png"), basename: "penguin", widths: [350, 700] },
];

const WIDTHS = [400, 800, 1200, 1600, 1920];
const AVIF_OPTS = { quality: 50, effort: 4 };
const WEBP_OPTS = { quality: 75, effort: 4 };
const JPEG_OPTS = { quality: 80, mozjpeg: true };
const PNG_OPTS = { compressionLevel: 9, palette: true };

async function isStale(srcPath, outPath) {
  if (!existsSync(outPath)) return true;
  const [s, o] = await Promise.all([stat(srcPath), stat(outPath)]);
  return s.mtimeMs > o.mtimeMs;
}

async function emitVariant(srcPath, outPath, width, ext) {
  const pipeline = sharp(srcPath).resize({ width, withoutEnlargement: true });
  if (ext === "avif") return pipeline.avif(AVIF_OPTS).toFile(outPath);
  if (ext === "webp") return pipeline.webp(WEBP_OPTS).toFile(outPath);
  if (ext === "jpg") return pipeline.jpeg(JPEG_OPTS).toFile(outPath);
  if (ext === "png") return pipeline.png(PNG_OPTS).toFile(outPath);
  throw new Error(`unknown ext ${ext}`);
}

async function processSource({ srcPath, basename, widths, fallbackExt }) {
  const meta = await sharp(srcPath).metadata();
  const sourceWidth = meta.width ?? widths[widths.length - 1];
  const targetWidths = [...new Set(widths.filter((w) => w <= sourceWidth))];
  if (targetWidths.length === 0 || targetWidths[targetWidths.length - 1] < sourceWidth) {
    if (sourceWidth <= widths[widths.length - 1]) targetWidths.push(sourceWidth);
  }

  const exts = ["avif", "webp", fallbackExt];
  let work = 0;
  for (const w of targetWidths) {
    for (const ext of exts) {
      const outPath = join(OUT_DIR, `${basename}-${w}.${ext}`);
      if (!(await isStale(srcPath, outPath))) continue;
      await emitVariant(srcPath, outPath, w, ext);
      work++;
    }
  }
  return { basename, widths: targetWidths, work };
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  const entries = await readdir(ROOT, { withFileTypes: true });
  const jpgs = entries
    .filter((e) => e.isFile() && /\.(jpe?g)$/i.test(e.name))
    .map((e) => e.name);

  const variants = {};
  let processed = 0;
  let skipped = 0;

  for (const file of jpgs) {
    const srcPath = join(ROOT, file);
    const { name } = parse(file);
    const r = await processSource({ srcPath, basename: name, widths: WIDTHS, fallbackExt: "jpg" });
    variants[name] = { widths: r.widths, fallbackExt: "jpg" };
    if (r.work) processed++;
    else skipped++;
  }
  for (const png of EXTRA_PNGS) {
    if (!existsSync(png.src)) continue;
    const r = await processSource({ srcPath: png.src, basename: png.basename, widths: png.widths, fallbackExt: "png" });
    variants[png.basename] = { widths: r.widths, fallbackExt: "png" };
    if (r.work) processed++;
    else skipped++;
  }

  const banner =
    "// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.\n" +
    "// Run `node scripts/optimize-images.mjs` (or `npm run prebuild`) to refresh.\n";
  const ts =
    banner +
    "export type ImageVariantInfo = { widths: number[]; fallbackExt: \"jpg\" | \"png\" };\n" +
    "export const imageVariants: Record<string, ImageVariantInfo> = " +
    JSON.stringify(variants, null, 2) +
    " as const;\n";
  await writeFile(MANIFEST_PATH, ts);

  console.log(`[optimize-images] processed=${processed} skipped=${skipped} (${jpgs.length} jpg + ${EXTRA_PNGS.length} png) -> ${MANIFEST_PATH}`);
}

main().catch((err) => {
  console.error("[optimize-images] failed:", err);
  process.exit(1);
});
